name: Python Linting

on:
  push:
  pull_request:

jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Install Python Deps
      run: python3 -m pip install flake8

    - name: Lint badger_os
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 badger_os

    - name: Lint examples
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 examples

    - name: Lint Badger 2040 W Libs
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 firmware/PIMORONI_BADGER2040W/lib

    - name: Lint Badger 2040 Libs
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 firmware/PIMORONI_BADGER2040/lib